### ISSUE TITLE
開發工具推薦：Codeium

### ISSUE THREAD

**Issue by moojing** [iAmCorey/awesome-indie-hacker-tools#2]
推薦另一套也還不錯用的代碼補全工具，之前沒有 copilot 的時候就是用這套
速度上慢了一點但堪用，想省錢的可以用這個作為 alternative
https://codeium.com/

**Comment by moojing** [comment]
<img width="992" alt="Screenshot 2024-10-13 at 11 27 25 PM" src="https://github.com/user-attachments/assets/7c9adc83-cc68-4de0-bb13-21bb6687a3f7">
個人使用是不用錢的

**Comment by iAmCorey** [comment]
已添加
